name: Build

on:
  push:
    branches: [ master, develop ]
    paths:
      - 'Jyutping/**'
      - 'Jyutping.sln'
      - '.github/workflows/**'
  pull_request:
    branches: [ master, develop ]
    paths:
      - 'Jyutping/**'
      - 'Jyutping.sln'
      - '.github/workflows/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: ${{ matrix.configuration }} ${{ matrix.platform }}
    strategy:
      matrix:
        configuration: [ Debug, Release ]
        platform: [ Win32, x64, ARM64, ARM64EC ]
      fail-fast: false

    runs-on: windows-2025-vs2026

    steps:
    - name: Checkout code
      uses: actions/checkout@v7

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v3
      with:
        msbuild-architecture: x64
        vs-version: '[18.0,19.0)'

    - name: Build solution
      run: msbuild Jyutping.sln -m -p:Configuration=${{ matrix.configuration }} -p:Platform=${{ matrix.platform }} -p:PreferredToolArchitecture=x64 -v:minimal
